apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: run-k6
spec:
  parallelism: 1
  starter:
    image: { STARTER_IMAGE }
  runner:
    image: { RUNNER_IMAGE }
  script:
    localFile: /test/test.js
